# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170425_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genreselect',
            name='Action',
            field=models.IntegerField(default=0, null=0),
        ),
    ]
