# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movies'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set([('user', 'movie_title')]),
        ),
    ]
