# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20170609_2311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set([]),
        ),
    ]
